use crate::{addressing_mode::*, bus::BusZ80, op, b, rg, rx, ri, rr, sp, am, sz, instruction_set::*, operation::Operation, register_set::{Register, RegisterType, IndexRegister}, Size};

pub(crate) fn opcode_table<T>() -> [Operation<T>; 0x100] where T: 'static + BusZ80 {
    [
        op!(0x00: b!(NOP)),                       op!(0x01: b!(LD), rg!(BC), am!(DD)),      op!(0x02: b!(LD), rg!(BC.b), rg!(A)),     op!(0x03: b!(INC), rg!(BC)),              op!(0x04: b!(INC), rg!(B)),               op!(0x05: b!(DEC), rg!(B)),               op!(0x06: b!(LD), rg!(B), am!(D)),         op!(0x07: b!(RLCA)),                      op!(0x08: b!(EX), rg!(AF), rg!(AF_)),    op!(0x09: b!(ADD), rg!(HL), rg!(BC)),    op!(0x0A: b!(LD), rg!(A), rg!(BC.b)),     op!(0x0B: b!(DEC), rg!(BC)),           op!(0x0C: b!(INC), rg!(C)),            op!(0x0D: b!(DEC), rg!(C)),            op!(0x0E: b!(LD), rg!(C), am!(D)),        op!(0x0F: b!(RRCA)),
        op!(0x10: b!(DJNZ), am!(D)),              op!(0x11: b!(LD), rg!(DE), am!(DD)),      op!(0x12: b!(LD), rg!(DE.b), rg!(A)),     op!(0x13: b!(INC), rg!(DE)),              op!(0x14: b!(INC), rg!(D)),               op!(0x15: b!(DEC), rg!(D)),               op!(0x16: b!(LD), rg!(D), am!(D)),         op!(0x17: b!(RLA)),                       op!(0x18: b!(JR UNC), am!(D)),           op!(0x19: b!(ADD), rg!(HL), rg!(DE)),    op!(0x1A: b!(LD), rg!(A), rg!(DE.b)),     op!(0x1B: b!(DEC), rg!(DE)),           op!(0x1C: b!(INC), rg!(E)),            op!(0x1D: b!(DEC), rg!(E)),            op!(0x1E: b!(LD), rg!(E), am!(D)),        op!(0x1F: b!(RRA)),
        op!(0x20: b!(JR NZ), am!(D)),             op!(0x21: b!(LD), rg!(HL), am!(DD)),      op!(0x22: b!(LD), am!(RR.w), rg!(HL)),    op!(0x23: b!(INC), rg!(HL)),              op!(0x24: b!(INC), rg!(H)),               op!(0x25: b!(DEC), rg!(H)),               op!(0x26: b!(LD), rg!(H), am!(D)),         op!(0x27: b!(DAA)),                       op!(0x28: b!(JR Z), am!(D)),             op!(0x29: b!(ADD), rg!(HL), rg!(HL)),    op!(0x2A: b!(LD), rg!(HL), am!(RR.w)),    op!(0x2B: b!(DEC), rg!(HL)),           op!(0x2C: b!(INC), rg!(L)),            op!(0x2D: b!(DEC), rg!(L)),            op!(0x2E: b!(LD), rg!(L), am!(D)),        op!(0x2F: b!(CPL)),
        op!(0x30: b!(JR NC), am!(D)),             op!(0x31: b!(LD), sp!(), am!(DD)),        op!(0x32: b!(LD), am!(RR.b), rg!(A)),     op!(0x33: b!(INC), sp!()),                op!(0x34: b!(INC), rg!(HL.b)),            op!(0x35: b!(DEC), rg!(HL.b)),            op!(0x36: b!(LD), rg!(HL.b), am!(D)),      op!(0x37: b!(SCF)),                       op!(0x38: b!(JR C), am!(D)),             op!(0x39: b!(ADD), rg!(HL), sp!()),      op!(0x3A: b!(LD), rg!(A), am!(RR.b)),     op!(0x3B: b!(DEC), sp!()),             op!(0x3C: b!(INC), rg!(A)),            op!(0x3D: b!(DEC), rg!(A)),            op!(0x3E: b!(LD), rg!(A), am!(D)),        op!(0x3F: b!(CCF)),
        op!(0x40: b!(LD), rg!(B), rg!(B)),        op!(0x41: b!(LD), rg!(B), rg!(C)),        op!(0x42: b!(LD), rg!(B), rg!(D)),        op!(0x43: b!(LD), rg!(B), rg!(E)),        op!(0x44: b!(LD), rg!(B), rg!(H)),        op!(0x45: b!(LD), rg!(B), rg!(L)),        op!(0x46: b!(LD), rg!(B), rg!(HL.b)),      op!(0x47: b!(LD), rg!(B), rg!(A)),        op!(0x48: b!(LD), rg!(C), rg!(B)),       op!(0x49: b!(LD), rg!(C), rg!(C)),       op!(0x4A: b!(LD), rg!(C), rg!(D)),        op!(0x4B: b!(LD), rg!(C), rg!(E)),     op!(0x4C: b!(LD), rg!(C), rg!(H)),     op!(0x4D: b!(LD), rg!(C), rg!(L)),     op!(0x4E: b!(LD), rg!(C), rg!(HL.b)),     op!(0x4F: b!(LD), rg!(C), rg!(A)),
        op!(0x50: b!(LD), rg!(D), rg!(B)),        op!(0x51: b!(LD), rg!(D), rg!(C)),        op!(0x52: b!(LD), rg!(D), rg!(D)),        op!(0x53: b!(LD), rg!(D), rg!(E)),        op!(0x54: b!(LD), rg!(D), rg!(H)),        op!(0x55: b!(LD), rg!(D), rg!(L)),        op!(0x56: b!(LD), rg!(D), rg!(HL.b)),      op!(0x57: b!(LD), rg!(D), rg!(A)),        op!(0x58: b!(LD), rg!(E), rg!(B)),       op!(0x59: b!(LD), rg!(E), rg!(C)),       op!(0x5A: b!(LD), rg!(E), rg!(D)),        op!(0x5B: b!(LD), rg!(E), rg!(E)),     op!(0x5C: b!(LD), rg!(E), rg!(H)),     op!(0x5D: b!(LD), rg!(E), rg!(L)),     op!(0x5E: b!(LD), rg!(E), rg!(HL.b)),     op!(0x5F: b!(LD), rg!(E), rg!(A)),
        op!(0x60: b!(LD), rg!(H), rg!(B)),        op!(0x61: b!(LD), rg!(H), rg!(C)),        op!(0x62: b!(LD), rg!(H), rg!(D)),        op!(0x63: b!(LD), rg!(H), rg!(E)),        op!(0x64: b!(LD), rg!(H), rg!(H)),        op!(0x65: b!(LD), rg!(H), rg!(L)),        op!(0x66: b!(LD), rg!(H), rg!(HL.b)),      op!(0x67: b!(LD), rg!(H), rg!(A)),        op!(0x68: b!(LD), rg!(L), rg!(B)),       op!(0x69: b!(LD), rg!(L), rg!(C)),       op!(0x6A: b!(LD), rg!(L), rg!(D)),        op!(0x6B: b!(LD), rg!(L), rg!(E)),     op!(0x6C: b!(LD), rg!(L), rg!(H)),     op!(0x6D: b!(LD), rg!(L), rg!(L)),     op!(0x6E: b!(LD), rg!(L), rg!(HL.b)),     op!(0x6F: b!(LD), rg!(L), rg!(A)),
        op!(0x70: b!(LD), rg!(HL.b), rg!(B)),     op!(0x71: b!(LD), rg!(HL.b), rg!(C)),     op!(0x72: b!(LD), rg!(HL.b), rg!(D)),     op!(0x73: b!(LD), rg!(HL.b), rg!(E)),     op!(0x74: b!(LD), rg!(HL.b), rg!(H)),     op!(0x75: b!(LD), rg!(HL.b), rg!(L)),     op!(0x76: b!(HALT)),                       op!(0x77: b!(LD), rg!(HL.b), rg!(A)),     op!(0x78: b!(LD), rg!(A), rg!(B)),       op!(0x79: b!(LD), rg!(A), rg!(C)),       op!(0x7A: b!(LD), rg!(A), rg!(D)),        op!(0x7B: b!(LD), rg!(A), rg!(E)),     op!(0x7C: b!(LD), rg!(A), rg!(H)),     op!(0x7D: b!(LD), rg!(A), rg!(L)),     op!(0x7E: b!(LD), rg!(A), rg!(HL.b)),     op!(0x7F: b!(LD), rg!(A), rg!(A)),
        op!(0x80: b!(ADD), rg!(A), rg!(B)),       op!(0x81: b!(ADD), rg!(A), rg!(C)),       op!(0x82: b!(ADD), rg!(A), rg!(D)),       op!(0x83: b!(ADD), rg!(A), rg!(E)),       op!(0x84: b!(ADD), rg!(A), rg!(H)),       op!(0x85: b!(ADD), rg!(A), rg!(L)),       op!(0x86: b!(ADD), rg!(A), rg!(HL.b)),     op!(0x87: b!(ADD), rg!(A), rg!(A)),       op!(0x88: b!(ADC), rg!(A), rg!(B)),      op!(0x89: b!(ADC), rg!(A), rg!(C)),      op!(0x8A: b!(ADC), rg!(A), rg!(D)),       op!(0x8B: b!(ADC), rg!(A), rg!(E)),    op!(0x8C: b!(ADC), rg!(A), rg!(H)),    op!(0x8D: b!(ADC), rg!(A), rg!(L)),    op!(0x8E: b!(ADC), rg!(A), rg!(HL.b)),    op!(0x8F: b!(ADC), rg!(A), rg!(A)),
        op!(0x90: b!(SUB), rg!(A), rg!(B)),       op!(0x91: b!(SUB), rg!(A), rg!(C)),       op!(0x92: b!(SUB), rg!(A), rg!(D)),       op!(0x93: b!(SUB), rg!(A), rg!(E)),       op!(0x94: b!(SUB), rg!(A), rg!(H)),       op!(0x95: b!(SUB), rg!(A), rg!(L)),       op!(0x96: b!(SUB), rg!(A), rg!(HL.b)),     op!(0x97: b!(SUB), rg!(A), rg!(A)),       op!(0x98: b!(SBC), rg!(A), rg!(B)),      op!(0x99: b!(SBC), rg!(A), rg!(C)),      op!(0x9A: b!(SBC), rg!(A), rg!(D)),       op!(0x9B: b!(SBC), rg!(A), rg!(E)),    op!(0x9C: b!(SBC), rg!(A), rg!(H)),    op!(0x9D: b!(SBC), rg!(A), rg!(L)),    op!(0x9E: b!(SBC), rg!(A), rg!(HL.b)),    op!(0x9F: b!(SBC), rg!(A), rg!(A)),
        op!(0xA0: b!(AND), rg!(A), rg!(B)),       op!(0xA1: b!(AND), rg!(A), rg!(C)),       op!(0xA2: b!(AND), rg!(A), rg!(D)),       op!(0xA3: b!(AND), rg!(A), rg!(E)),       op!(0xA4: b!(AND), rg!(A), rg!(H)),       op!(0xA5: b!(AND), rg!(A), rg!(L)),       op!(0xA6: b!(AND), rg!(A), rg!(HL.b)),     op!(0xA7: b!(AND), rg!(A), rg!(A)),       op!(0xA8: b!(XOR), rg!(A), rg!(B)),      op!(0xA9: b!(XOR), rg!(A), rg!(C)),      op!(0xAA: b!(XOR), rg!(A), rg!(D)),       op!(0xAB: b!(XOR), rg!(A), rg!(E)),    op!(0xAC: b!(XOR), rg!(A), rg!(H)),    op!(0xAD: b!(XOR), rg!(A), rg!(L)),    op!(0xAE: b!(XOR), rg!(A), rg!(HL.b)),    op!(0xAF: b!(XOR), rg!(A), rg!(A)),
        op!(0xB0: b!(OR), rg!(A), rg!(B)),        op!(0xB1: b!(OR), rg!(A), rg!(C)),        op!(0xB2: b!(OR), rg!(A), rg!(D)),        op!(0xB3: b!(OR), rg!(A), rg!(E)),        op!(0xB4: b!(OR), rg!(A), rg!(H)),        op!(0xB5: b!(OR), rg!(A), rg!(L)),        op!(0xB6: b!(OR), rg!(A), rg!(HL.b)),      op!(0xB7: b!(OR), rg!(A), rg!(A)),        op!(0xB8: b!(CP), rg!(A), rg!(B)),       op!(0xB9: b!(CP), rg!(A), rg!(C)),       op!(0xBA: b!(CP), rg!(A), rg!(D)),        op!(0xBB: b!(CP), rg!(A), rg!(E)),     op!(0xBC: b!(CP), rg!(A), rg!(H)),     op!(0xBD: b!(CP), rg!(A), rg!(L)),     op!(0xBE: b!(CP), rg!(A), rg!(HL.b)),     op!(0xBF: b!(CP), rg!(A), rg!(A)),
        op!(0xC0: b!(RET NZ)),                    op!(0xC1: b!(POP), rg!(BC)),              op!(0xC2: b!(JP NZ), am!(DD)),            op!(0xC3: b!(JP UNC), am!(DD)),           op!(0xC4: b!(CALL NZ), am!(DD)),          op!(0xC5: b!(PUSH), rg!(BC)),             op!(0xC6: b!(ADD), rg!(A), am!(D)),        op!(0xC7: b!(RST 0x00)),                  op!(0xC8: b!(RET Z)),                    op!(0xC9: b!(RET UNC)),                  op!(0xCA: b!(JP Z), am!(DD)),             op!(0xCB: b!(NOP)),                    op!(0xCC: b!(CALL Z), am!(DD)),        op!(0xCD: b!(CALL UNC), am!(DD)),      op!(0xCE: b!(ADC), rg!(A), am!(D)),       op!(0xCF: b!(RST 0x08)),
        op!(0xD0: b!(RET NC)),                    op!(0xD1: b!(POP), rg!(DE)),              op!(0xD2: b!(JP NC), am!(DD)),            op!(0xD3: b!(OUT), am!(R), rg!(A)),       op!(0xD4: b!(CALL NC), am!(DD)),          op!(0xD5: b!(PUSH), rg!(DE)),             op!(0xD6: b!(SUB), rg!(A), am!(D)),        op!(0xD7: b!(RST 0x10)),                  op!(0xD8: b!(RET C)),                    op!(0xD9: b!(EXX)),                      op!(0xDA: b!(JP C), am!(DD)),             op!(0xDB: b!(IN), rg!(A), am!(R)),     op!(0xDC: b!(CALL C), am!(DD)),        op!(0xDD: b!(NOP)),                    op!(0xDE: b!(SBC), rg!(A), am!(D)),       op!(0xDF: b!(RST 0x18)),
        op!(0xE0: b!(RET PO)),                    op!(0xE1: b!(POP), rg!(HL)),              op!(0xE2: b!(JP PO), am!(DD)),            op!(0xE3: b!(EX), sp!(w), rg!(HL)),       op!(0xE4: b!(CALL PO), am!(DD)),          op!(0xE5: b!(PUSH), rg!(HL)),             op!(0xE6: b!(AND), rg!(A), am!(D)),        op!(0xE7: b!(RST 0x20)),                  op!(0xE8: b!(RET PE)),                   op!(0xE9: b!(JP UNC), rg!(HL.w)),        op!(0xEA: b!(JP PE), am!(DD)),            op!(0xEB: b!(EX), rg!(DE), rg!(HL)),   op!(0xEC: b!(CALL PE), am!(DD)),       op!(0xED: b!(NOP)),                    op!(0xEE: b!(XOR), rg!(A), am!(D)),       op!(0xEF: b!(RST 0x28)),
        op!(0xF0: b!(RET P)),                     op!(0xF1: b!(POP), rg!(AF)),              op!(0xF2: b!(JP P), am!(DD)),             op!(0xF3: b!(DI)),                        op!(0xF4: b!(CALL P), am!(DD)),           op!(0xF5: b!(PUSH), rg!(AF)),             op!(0xF6: b!(OR), rg!(A), am!(D)),         op!(0xF7: b!(RST 0x30)),                  op!(0xF8: b!(RET M)),                    op!(0xF9: b!(LD), sp!(), rg!(HL)),       op!(0xFA: b!(JP M), am!(DD)),             op!(0xFB: b!(EI)),                     op!(0xFC: b!(CALL M), am!(DD)),        op!(0xFD: b!(NOP)),                    op!(0xFE: b!(CP), rg!(A), am!(D)),        op!(0xFF: b!(RST 0x38)),
    ]
}

pub(crate) fn ed_opcode_table<T>() -> [Operation<T>; 0x100] where T: 'static + BusZ80 {
    [
        op!(0x00: b!(XEP)),                     op!(0x01: b!(XEP)),                      op!(0x02: b!(XEP)),                      op!(0x03: b!(XEP)),                     op!(0x04: b!(XEP)),            op!(0x05: b!(XEP)),     op!(0x06: b!(XEP)),                     op!(0x07: b!(XEP)),                  op!(0x08: b!(XEP)),                      op!(0x09: b!(XEP)),                       op!(0x0A: b!(XEP)),                      op!(0x0B: b!(XEP)),                    op!(0x0C: b!(XEP)),    op!(0x0D: b!(XEP)),     op!(0x0E: b!(XEP)),                      op!(0x0F: b!(XEP)),
        op!(0x10: b!(XEP)),                     op!(0x11: b!(XEP)),                      op!(0x12: b!(XEP)),                      op!(0x13: b!(XEP)),                     op!(0x14: b!(XEP)),            op!(0x15: b!(XEP)),     op!(0x16: b!(XEP)),                     op!(0x17: b!(XEP)),                  op!(0x18: b!(XEP)),                      op!(0x19: b!(XEP)),                       op!(0x1A: b!(XEP)),                      op!(0x1B: b!(XEP)),                    op!(0x1C: b!(XEP)),    op!(0x1D: b!(XEP)),     op!(0x1E: b!(XEP)),                      op!(0x1F: b!(XEP)),
        op!(0x20: b!(XEP)),                     op!(0x21: b!(XEP)),                      op!(0x22: b!(XEP)),                      op!(0x23: b!(XEP)),                     op!(0x24: b!(XEP)),            op!(0x25: b!(XEP)),     op!(0x26: b!(XEP)),                     op!(0x27: b!(XEP)),                  op!(0x28: b!(XEP)),                      op!(0x29: b!(XEP)),                       op!(0x2A: b!(XEP)),                      op!(0x2B: b!(XEP)),                    op!(0x2C: b!(XEP)),    op!(0x2D: b!(XEP)),     op!(0x2E: b!(XEP)),                      op!(0x2F: b!(XEP)),
        op!(0x30: b!(XEP)),                     op!(0x31: b!(XEP)),                      op!(0x32: b!(XEP)),                      op!(0x33: b!(XEP)),                     op!(0x34: b!(XEP)),            op!(0x35: b!(XEP)),     op!(0x36: b!(XEP)),                     op!(0x37: b!(XEP)),                  op!(0x38: b!(XEP)),                      op!(0x39: b!(XEP)),                       op!(0x3A: b!(XEP)),                      op!(0x3B: b!(XEP)),                    op!(0x3C: b!(XEP)),    op!(0x3D: b!(XEP)),     op!(0x3E: b!(XEP)),                      op!(0x3F: b!(XEP)),
        op!(0x40: b!(IN), rg!(B), rg!(C.b)),    op!(0x41: b!(OUT), rg!(C.b), rg!(B)),    op!(0x42: b!(SBC), rg!(HL), rg!(BC)),    op!(0x43: b!(LD), am!(DD), rg!(BC)),    op!(0x44: b!(NEG), rg!(A)),    op!(0x45: b!(RETN)),    op!(0x46: b!(IM 0)),                    op!(0x47: b!(LD), ri!(), rg!(A)),    op!(0x48: b!(IN), rg!(C), rg!(BC.b)),    op!(0x49: b!(OUT), rg!(BC.b), rg!(C)),    op!(0x4A: b!(ADC), rg!(HL), rg!(BC)),    op!(0x4B: b!(LD), rg!(BC), am!(DD)),   op!(0x4C: b!(XEP)),    op!(0x4D: b!(RETI)),    op!(0x4E: b!(LD), rg!(C), rx!(X.b)),     op!(0x4F: b!(LD), rr!(), rg!(A)),
        op!(0x50: b!(IN), rg!(D), rg!(C.b)),    op!(0x51: b!(OUT), rg!(C.b), rg!(D)),    op!(0x52: b!(SBC), rg!(HL), rg!(DE)),    op!(0x53: b!(LD), am!(DD), rg!(DE)),    op!(0x54: b!(XEP)),            op!(0x55: b!(XEP)),     op!(0x56: b!(IM 1)),                    op!(0x57: b!(LD), rg!(A), ri!()),    op!(0x58: b!(IN), rg!(E), rg!(BC.b)),    op!(0x59: b!(OUT), rg!(BC.b), rg!(E)),    op!(0x5A: b!(ADC), rg!(HL), rg!(DE)),    op!(0x5B: b!(LD), rg!(DE), am!(DD)),   op!(0x5C: b!(XEP)),    op!(0x5D: b!(XEP)),     op!(0x5E: b!(IM 2)),                     op!(0x5F: b!(LD), rg!(A), rr!()),
        op!(0x60: b!(IN), rg!(H), rg!(C.b)),    op!(0x61: b!(OUT), rg!(C.b), rg!(H)),    op!(0x62: b!(SBC), rg!(HL), rg!(HL)),    op!(0x63: b!(XEP)),                     op!(0x64: b!(XEP)),            op!(0x65: b!(XEP)),     op!(0x66: b!(LD), rg!(H), rx!(X.b)),    op!(0x67: b!(RRD), rg!(HL.b)),       op!(0x68: b!(IN), rg!(L), rg!(BC.b)),    op!(0x69: b!(OUT), rg!(BC.b), rg!(L)),    op!(0x6A: b!(ADC), rg!(HL), rg!(HL)),    op!(0x6B: b!(XEP)),                    op!(0x6C: b!(XEP)),    op!(0x6D: b!(XEP)),     op!(0x6E: b!(LD), rg!(L), rx!(X.b)),     op!(0x6F: b!(RLD), rg!(HL.b)),
        op!(0x70: b!(XEP)),                     op!(0x71: b!(XEP)),                      op!(0x72: b!(SBC), rg!(HL), sp!()),      op!(0x73: b!(LD), am!(DD), sp!()),      op!(0x74: b!(XEP)),            op!(0x75: b!(XEP)),     op!(0x76: b!(XEP)),                     op!(0x77: b!(XEP)),                  op!(0x78: b!(IN), rg!(A), rg!(BC.b)),    op!(0x79: b!(OUT), rg!(BC.b), rg!(A)),    op!(0x7A: b!(ADC), rg!(HL), sp!()),      op!(0x7B: b!(LD), sp!(), am!(DD)),     op!(0x7C: b!(XEP)),    op!(0x7D: b!(XEP)),     op!(0x7E: b!(XEP)),                      op!(0x7F: b!(XEP)),
        op!(0x80: b!(XEP)),                     op!(0x81: b!(XEP)),                      op!(0x82: b!(XEP)),                      op!(0x83: b!(XEP)),                     op!(0x84: b!(XEP)),            op!(0x85: b!(XEP)),     op!(0x86: b!(XEP)),                     op!(0x87: b!(XEP)),                  op!(0x88: b!(XEP)),                      op!(0x89: b!(XEP)),                       op!(0x8A: b!(XEP)),                      op!(0x8B: b!(XEP)),                    op!(0x8C: b!(XEP)),    op!(0x8D: b!(XEP)),     op!(0x8E: b!(XEP)),                      op!(0x8F: b!(XEP)),
        op!(0x90: b!(XEP)),                     op!(0x91: b!(XEP)),                      op!(0x92: b!(XEP)),                      op!(0x93: b!(XEP)),                     op!(0x94: b!(XEP)),            op!(0x95: b!(XEP)),     op!(0x96: b!(XEP)),                     op!(0x97: b!(XEP)),                  op!(0x98: b!(XEP)),                      op!(0x99: b!(XEP)),                       op!(0x9A: b!(XEP)),                      op!(0x9B: b!(XEP)),                    op!(0x9C: b!(XEP)),    op!(0x9D: b!(XEP)),     op!(0x9E: b!(XEP)),                      op!(0x9F: b!(XEP)),
        op!(0xA0: b!(LDI)),                     op!(0xA1: b!(CPI)),                      op!(0xA2: b!(INI)),                      op!(0xA3: b!(OUTI)),                    op!(0xA4: b!(XEP)),            op!(0xA5: b!(XEP)),     op!(0xA6: b!(XEP)),                     op!(0xA7: b!(XEP)),                  op!(0xA8: b!(LDD)),                      op!(0xA9: b!(CPD)),                       op!(0xAA: b!(IND)),                      op!(0xAB: b!(OUTD)),                   op!(0xAC: b!(XEP)),    op!(0xAD: b!(XEP)),     op!(0xAE: b!(XOR), rg!(A), rx!(X.b)),    op!(0xAF: b!(XEP)),
        op!(0xB0: b!(LDIR)),                    op!(0xB1: b!(CPIR)),                     op!(0xB2: b!(INIR)),                     op!(0xB3: b!(OTIR)),                    op!(0xB4: b!(XEP)),            op!(0xB5: b!(XEP)),     op!(0xB6: b!(XEP)),                     op!(0xB7: b!(XEP)),                  op!(0xB8: b!(LDDR)),                     op!(0xB9: b!(CPDR)),                      op!(0xBA: b!(INDR)),                     op!(0xBB: b!(OTDR)),                   op!(0xBC: b!(XEP)),    op!(0xBD: b!(XEP)),     op!(0xBE: b!(XEP)),                      op!(0xBF: b!(XEP)),
        op!(0xC0: b!(XEP)),                     op!(0xC1: b!(XEP)),                      op!(0xC2: b!(XEP)),                      op!(0xC3: b!(XEP)),                     op!(0xC4: b!(XEP)),            op!(0xC5: b!(XEP)),     op!(0xC6: b!(XEP)),                     op!(0xC7: b!(XEP)),                  op!(0xC8: b!(XEP)),                      op!(0xC9: b!(XEP)),                       op!(0xCA: b!(XEP)),                      op!(0xCB: b!(XEP)),                    op!(0xCC: b!(XEP)),    op!(0xCD: b!(XEP)),     op!(0xCE: b!(XEP)),                      op!(0xCF: b!(XEP)),
        op!(0xD0: b!(XEP)),                     op!(0xD1: b!(XEP)),                      op!(0xD2: b!(XEP)),                      op!(0xD3: b!(XEP)),                     op!(0xD4: b!(XEP)),            op!(0xD5: b!(XEP)),     op!(0xD6: b!(XEP)),                     op!(0xD7: b!(XEP)),                  op!(0xD8: b!(XEP)),                      op!(0xD9: b!(XEP)),                       op!(0xDA: b!(XEP)),                      op!(0xDB: b!(XEP)),                    op!(0xDC: b!(XEP)),    op!(0xDD: b!(XEP)),     op!(0xDE: b!(XEP)),                      op!(0xDF: b!(XEP)),
        op!(0xE0: b!(XEP)),                     op!(0xE1: b!(XEP)),                      op!(0xE2: b!(XEP)),                      op!(0xE3: b!(XEP)),                     op!(0xE4: b!(XEP)),            op!(0xE5: b!(XEP)),     op!(0xE6: b!(XEP)),                     op!(0xE7: b!(XEP)),                  op!(0xE8: b!(XEP)),                      op!(0xE9: b!(XEP)),                       op!(0xEA: b!(XEP)),                      op!(0xEB: b!(XEP)),                    op!(0xEC: b!(XEP)),    op!(0xED: b!(XEP)),     op!(0xEE: b!(XEP)),                      op!(0xEF: b!(XEP)),
        op!(0xF0: b!(XEP)),                     op!(0xF1: b!(XEP)),                      op!(0xF2: b!(XEP)),                      op!(0xF3: b!(XEP)),                     op!(0xF4: b!(XEP)),            op!(0xF5: b!(XEP)),     op!(0xF6: b!(XEP)),                     op!(0xF7: b!(XEP)),                  op!(0xF8: b!(XEP)),                      op!(0xF9: b!(XEP)),                       op!(0xFA: b!(XEP)),                      op!(0xFB: b!(XEP)),                    op!(0xFC: b!(XEP)),    op!(0xFD: b!(XEP)),     op!(0xFE: b!(XEP)),                      op!(0xFF: b!(XEP)),
    ]
}

pub(crate) fn cb_opcode_table<T>() -> [Operation<T>; 0x100] where T: 'static + BusZ80 {
    [
        op!(0x00: b!(RLC), rg!(B)),      op!(0x01: b!(RLC), rg!(C)),      op!(0x02: b!(RLC), rg!(D)),      op!(0x03: b!(RLC), rg!(E)),      op!(0x04: b!(RLC), rg!(H)),      op!(0x05: b!(RLC), rg!(L)),      op!(0x06: b!(RLC), rg!(HL.b)),      op!(0x07: b!(RLC), rg!(A)),      op!(0x08: b!(RRC), rg!(B)),      op!(0x09: b!(RRC), rg!(C)),      op!(0x0A: b!(RRC), rg!(D)),       op!(0x0B: b!(RRC), rg!(E)),      op!(0x0C: b!(RRC), rg!(H)),      op!(0x0D: b!(RRC), rg!(L)),      op!(0x0E: b!(RRC), rg!(HL.b)),      op!(0x0F: b!(RRC), rg!(A)),
        op!(0x10: b!(RL), rg!(B)),       op!(0x11: b!(RL), rg!(C)),       op!(0x12: b!(RL), rg!(D)),       op!(0x13: b!(RL), rg!(E)),       op!(0x14: b!(RL), rg!(H)),       op!(0x15: b!(RL), rg!(L)),       op!(0x16: b!(RL), rg!(HL.b)),       op!(0x17: b!(RL), rg!(A)),       op!(0x18: b!(RR), rg!(B)),       op!(0x19: b!(RR), rg!(C)),       op!(0x1A: b!(RR), rg!(D)),        op!(0x1B: b!(RR), rg!(E)),       op!(0x1C: b!(RR), rg!(H)),       op!(0x1D: b!(RR), rg!(L)),       op!(0x1E: b!(RR), rg!(HL.b)),       op!(0x1F: b!(RR), rg!(A)),
        op!(0x20: b!(SLA), rg!(B)),      op!(0x21: b!(SLA), rg!(C)),      op!(0x22: b!(SLA), rg!(D)),      op!(0x23: b!(SLA), rg!(E)),      op!(0x24: b!(SLA), rg!(H)),      op!(0x25: b!(SLA), rg!(L)),      op!(0x26: b!(SLA), rg!(HL.b)),      op!(0x27: b!(SLA), rg!(A)),      op!(0x28: b!(SRA), rg!(B)),      op!(0x29: b!(SRA), rg!(C)),      op!(0x2A: b!(SRA), rg!(D)),       op!(0x2B: b!(SRA), rg!(E)),      op!(0x2C: b!(SRA), rg!(H)),      op!(0x2D: b!(SRA), rg!(L)),      op!(0x2E: b!(SRA), rg!(HL.b)),      op!(0x2F: b!(SRA), rg!(A)),
        op!(0x30: b!(NOP)),              op!(0x31: b!(NOP)),              op!(0x32: b!(NOP)),              op!(0x33: b!(NOP)),              op!(0x34: b!(NOP)),              op!(0x35: b!(NOP)),              op!(0x36: b!(NOP)),                 op!(0x37: b!(NOP)),              op!(0x38: b!(SRL), rg!(B)),      op!(0x39: b!(SRL), rg!(C)),      op!(0x3A: b!(SRL), rg!(D)),       op!(0x3B: b!(SRL), rg!(E)),      op!(0x3C: b!(SRL), rg!(H)),      op!(0x3D: b!(SRL), rg!(L)),      op!(0x3E: b!(SRL), rg!(HL.b)),      op!(0x3F: b!(SRL), rg!(A)),
        op!(0x40: b!(BIT 0), rg!(B)),    op!(0x41: b!(BIT 0), rg!(C)),    op!(0x42: b!(BIT 0), rg!(D)),    op!(0x43: b!(BIT 0), rg!(E)),    op!(0x44: b!(BIT 0), rg!(H)),    op!(0x45: b!(BIT 0), rg!(L)),    op!(0x46: b!(BIT 0), rg!(HL.b)),    op!(0x47: b!(BIT 0), rg!(A)),    op!(0x48: b!(BIT 1), rg!(B)),    op!(0x49: b!(BIT 1), rg!(C)),    op!(0x4A: b!(BIT  1), rg!(D)),    op!(0x4B: b!(BIT 1), rg!(E)),    op!(0x4C: b!(BIT 1), rg!(H)),    op!(0x4D: b!(BIT 1), rg!(L)),    op!(0x4E: b!(BIT 1), rg!(HL.b)),    op!(0x4F: b!(BIT 1), rg!(A)),
        op!(0x50: b!(BIT 2), rg!(B)),    op!(0x51: b!(BIT 2), rg!(C)),    op!(0x52: b!(BIT 2), rg!(D)),    op!(0x53: b!(BIT 2), rg!(E)),    op!(0x54: b!(BIT 2), rg!(H)),    op!(0x55: b!(BIT 2), rg!(L)),    op!(0x56: b!(BIT 2), rg!(HL.b)),    op!(0x57: b!(BIT 2), rg!(A)),    op!(0x58: b!(BIT 3), rg!(B)),    op!(0x59: b!(BIT 3), rg!(C)),    op!(0x5A: b!(BIT  3), rg!(D)),    op!(0x5B: b!(BIT 3), rg!(E)),    op!(0x5C: b!(BIT 3), rg!(H)),    op!(0x5D: b!(BIT 3), rg!(L)),    op!(0x5E: b!(BIT 3), rg!(HL.b)),    op!(0x5F: b!(BIT 3), rg!(A)),
        op!(0x60: b!(BIT 4), rg!(B)),    op!(0x61: b!(BIT 4), rg!(C)),    op!(0x62: b!(BIT 4), rg!(D)),    op!(0x63: b!(BIT 4), rg!(E)),    op!(0x64: b!(BIT 4), rg!(H)),    op!(0x65: b!(BIT 4), rg!(L)),    op!(0x66: b!(BIT 4), rg!(HL.b)),    op!(0x67: b!(BIT 4), rg!(A)),    op!(0x68: b!(BIT 5), rg!(B)),    op!(0x69: b!(BIT 5), rg!(C)),    op!(0x6A: b!(BIT  5), rg!(D)),    op!(0x6B: b!(BIT 5), rg!(E)),    op!(0x6C: b!(BIT 5), rg!(H)),    op!(0x6D: b!(BIT 5), rg!(L)),    op!(0x6E: b!(BIT 5), rg!(HL.b)),    op!(0x6F: b!(BIT 5), rg!(A)),
        op!(0x70: b!(BIT 6), rg!(B)),    op!(0x71: b!(BIT 6), rg!(C)),    op!(0x72: b!(BIT 6), rg!(D)),    op!(0x73: b!(BIT 6), rg!(E)),    op!(0x74: b!(BIT 6), rg!(H)),    op!(0x75: b!(BIT 6), rg!(L)),    op!(0x76: b!(BIT 6), rg!(HL.b)),    op!(0x77: b!(BIT 6), rg!(A)),    op!(0x78: b!(BIT 7), rg!(B)),    op!(0x79: b!(BIT 7), rg!(C)),    op!(0x7A: b!(BIT  7), rg!(D)),    op!(0x7B: b!(BIT 7), rg!(E)),    op!(0x7C: b!(BIT 7), rg!(H)),    op!(0x7D: b!(BIT 7), rg!(L)),    op!(0x7E: b!(BIT 7), rg!(HL.b)),    op!(0x7F: b!(BIT 7), rg!(A)),
        op!(0x80: b!(RES 0), rg!(B)),    op!(0x81: b!(RES 0), rg!(C)),    op!(0x82: b!(RES 0), rg!(D)),    op!(0x83: b!(RES 0), rg!(E)),    op!(0x84: b!(RES 0), rg!(H)),    op!(0x85: b!(RES 0), rg!(L)),    op!(0x86: b!(RES 0), rg!(HL.b)),    op!(0x87: b!(RES 0), rg!(A)),    op!(0x88: b!(RES 1), rg!(B)),    op!(0x89: b!(RES 1), rg!(C)),    op!(0x8A: b!(RES 1), rg!(D)),     op!(0x8B: b!(RES 1), rg!(E)),    op!(0x8C: b!(RES 1), rg!(H)),    op!(0x8D: b!(RES 1), rg!(L)),    op!(0x8E: b!(RES 1), rg!(HL.b)),    op!(0x8F: b!(RES 1), rg!(A)),
        op!(0x90: b!(RES 2), rg!(B)),    op!(0x91: b!(RES 2), rg!(C)),    op!(0x92: b!(RES 2), rg!(D)),    op!(0x93: b!(RES 2), rg!(E)),    op!(0x94: b!(RES 2), rg!(H)),    op!(0x95: b!(RES 2), rg!(L)),    op!(0x96: b!(RES 2), rg!(HL.b)),    op!(0x97: b!(RES 2), rg!(A)),    op!(0x98: b!(RES 3), rg!(B)),    op!(0x99: b!(RES 3), rg!(C)),    op!(0x9A: b!(RES 3), rg!(D)),     op!(0x9B: b!(RES 3), rg!(E)),    op!(0x9C: b!(RES 3), rg!(H)),    op!(0x9D: b!(RES 3), rg!(L)),    op!(0x9E: b!(RES 3), rg!(HL.b)),    op!(0x9F: b!(RES 3), rg!(A)),
        op!(0xA0: b!(RES 4), rg!(B)),    op!(0xA1: b!(RES 4), rg!(C)),    op!(0xA2: b!(RES 4), rg!(D)),    op!(0xA3: b!(RES 4), rg!(E)),    op!(0xA4: b!(RES 4), rg!(H)),    op!(0xA5: b!(RES 4), rg!(L)),    op!(0xA6: b!(RES 4), rg!(HL.b)),    op!(0xA7: b!(RES 4), rg!(A)),    op!(0xA8: b!(RES 5), rg!(B)),    op!(0xA9: b!(RES 5), rg!(C)),    op!(0xAA: b!(RES 5), rg!(D)),     op!(0xAB: b!(RES 5), rg!(E)),    op!(0xAC: b!(RES 5), rg!(H)),    op!(0xAD: b!(RES 5), rg!(L)),    op!(0xAE: b!(RES 5), rg!(HL.b)),    op!(0xAF: b!(RES 5), rg!(A)),
        op!(0xB0: b!(RES 6), rg!(B)),    op!(0xB1: b!(RES 6), rg!(C)),    op!(0xB2: b!(RES 6), rg!(D)),    op!(0xB3: b!(RES 6), rg!(E)),    op!(0xB4: b!(RES 6), rg!(H)),    op!(0xB5: b!(RES 6), rg!(L)),    op!(0xB6: b!(RES 6), rg!(HL.b)),    op!(0xB7: b!(RES 6), rg!(A)),    op!(0xB8: b!(RES 7), rg!(B)),    op!(0xB9: b!(RES 7), rg!(C)),    op!(0xBA: b!(RES 7), rg!(D)),     op!(0xBB: b!(RES 7), rg!(E)),    op!(0xBC: b!(RES 7), rg!(H)),    op!(0xBD: b!(RES 7), rg!(L)),    op!(0xBE: b!(RES 7), rg!(HL.b)),    op!(0xBF: b!(RES 7), rg!(A)),
        op!(0xC0: b!(SET 0), rg!(B)),    op!(0xC1: b!(SET 0), rg!(C)),    op!(0xC2: b!(SET 0), rg!(D)),    op!(0xC3: b!(SET 0), rg!(E)),    op!(0xC4: b!(SET 0), rg!(H)),    op!(0xC5: b!(SET 0), rg!(L)),    op!(0xC6: b!(SET 0), rg!(HL.b)),    op!(0xC7: b!(SET 0), rg!(A)),    op!(0xC8: b!(SET 1), rg!(B)),    op!(0xC9: b!(SET 1), rg!(C)),    op!(0xCA: b!(SET 1), rg!(D)),     op!(0xCB: b!(SET 1), rg!(E)),    op!(0xCC: b!(SET 1), rg!(H)),    op!(0xCD: b!(SET 1), rg!(L)),    op!(0xCE: b!(SET 1), rg!(HL.b)),    op!(0xCF: b!(SET 1), rg!(A)),
        op!(0xD0: b!(SET 2), rg!(B)),    op!(0xD1: b!(SET 2), rg!(C)),    op!(0xD2: b!(SET 2), rg!(D)),    op!(0xD3: b!(SET 2), rg!(E)),    op!(0xD4: b!(SET 2), rg!(H)),    op!(0xD5: b!(SET 2), rg!(L)),    op!(0xD6: b!(SET 2), rg!(HL.b)),    op!(0xD7: b!(SET 2), rg!(A)),    op!(0xD8: b!(SET 3), rg!(B)),    op!(0xD9: b!(SET 3), rg!(C)),    op!(0xDA: b!(SET 3), rg!(D)),     op!(0xDB: b!(SET 3), rg!(E)),    op!(0xDC: b!(SET 3), rg!(H)),    op!(0xDD: b!(SET 3), rg!(L)),    op!(0xDE: b!(SET 3), rg!(HL.b)),    op!(0xDF: b!(SET 3), rg!(A)),
        op!(0xE0: b!(SET 4), rg!(B)),    op!(0xE1: b!(SET 4), rg!(C)),    op!(0xE2: b!(SET 4), rg!(D)),    op!(0xE3: b!(SET 4), rg!(E)),    op!(0xE4: b!(SET 4), rg!(H)),    op!(0xE5: b!(SET 4), rg!(L)),    op!(0xE6: b!(SET 4), rg!(HL.b)),    op!(0xE7: b!(SET 4), rg!(A)),    op!(0xE8: b!(SET 5), rg!(B)),    op!(0xE9: b!(SET 5), rg!(C)),    op!(0xEA: b!(SET 5), rg!(D)),     op!(0xEB: b!(SET 5), rg!(E)),    op!(0xEC: b!(SET 5), rg!(H)),    op!(0xED: b!(SET 5), rg!(L)),    op!(0xEE: b!(SET 5), rg!(HL.b)),    op!(0xEF: b!(SET 5), rg!(A)),
        op!(0xF0: b!(SET 6), rg!(B)),    op!(0xF1: b!(SET 6), rg!(C)),    op!(0xF2: b!(SET 6), rg!(D)),    op!(0xF3: b!(SET 6), rg!(E)),    op!(0xF4: b!(SET 6), rg!(H)),    op!(0xF5: b!(SET 6), rg!(L)),    op!(0xF6: b!(SET 6), rg!(HL.b)),    op!(0xF7: b!(SET 6), rg!(A)),    op!(0xF8: b!(SET 7), rg!(B)),    op!(0xF9: b!(SET 7), rg!(C)),    op!(0xFA: b!(SET 7), rg!(D)),     op!(0xFB: b!(SET 7), rg!(E)),    op!(0xFC: b!(SET 7), rg!(H)),    op!(0xFD: b!(SET 7), rg!(L)),    op!(0xFE: b!(SET 7), rg!(HL.b)),    op!(0xFF: b!(SET 7), rg!(A)),
    ]
}

pub(crate) fn dd_opcode_table<T>() -> [Operation<T>; 0x100] where T: 'static + BusZ80 {
    [
        op!(0x00: b!(XEP)),                     op!(0x01: b!(XEP)),                     op!(0x02: b!(XEP)),                     op!(0x03: b!(XEP)),                     op!(0x04: b!(XEP)),                     op!(0x05: b!(XEP)),                     op!(0x06: b!(XEP)),                     op!(0x07: b!(XEP)),                     op!(0x08: b!(XEP)),    op!(0x09: b!(ADD), rx!(X), rg!(BC)),    op!(0x0A: b!(XEP)),                    op!(0x0B: b!(XEP)),            op!(0x0C: b!(XEP)),    op!(0x0D: b!(XEP)),    op!(0x0E: b!(XEP)),                      op!(0x0F: b!(XEP)),
        op!(0x10: b!(XEP)),                     op!(0x11: b!(XEP)),                     op!(0x12: b!(XEP)),                     op!(0x13: b!(XEP)),                     op!(0x14: b!(XEP)),                     op!(0x15: b!(XEP)),                     op!(0x16: b!(XEP)),                     op!(0x17: b!(XEP)),                     op!(0x18: b!(XEP)),    op!(0x19: b!(ADD), rx!(X), rg!(DE)),    op!(0x1A: b!(XEP)),                    op!(0x1B: b!(XEP)),            op!(0x1C: b!(XEP)),    op!(0x1D: b!(XEP)),    op!(0x1E: b!(XEP)),                      op!(0x1F: b!(XEP)),
        op!(0x20: b!(XEP)),                     op!(0x21: b!(LD), rx!(X), am!(DD)),     op!(0x22: b!(LD), am!(DD), rx!(X)),     op!(0x23: b!(INC), rx!(X)),             op!(0x24: b!(XEP)),                     op!(0x25: b!(XEP)),                     op!(0x26: b!(XEP)),                     op!(0x27: b!(XEP)),                     op!(0x28: b!(XEP)),    op!(0x29: b!(ADD), rx!(X), rx!(X)),     op!(0x2A: b!(LD), rx!(X), am!(DD)),    op!(0x2B: b!(DEC), rx!(X)),    op!(0x2C: b!(XEP)),    op!(0x2D: b!(XEP)),    op!(0x2E: b!(XEP)),                      op!(0x2F: b!(XEP)),
        op!(0x30: b!(XEP)),                     op!(0x31: b!(XEP)),                     op!(0x32: b!(XEP)),                     op!(0x33: b!(XEP)),                     op!(0x34: b!(INC), rx!(X.b)),           op!(0x35: b!(DEC), rx!(X.b)),           op!(0x36: b!(LD), rx!(X.b), am!(D)),    op!(0x37: b!(XEP)),                     op!(0x38: b!(XEP)),    op!(0x39: b!(ADD), rx!(X), sp!()),      op!(0x3A: b!(XEP)),                    op!(0x3B: b!(XEP)),            op!(0x3C: b!(XEP)),    op!(0x3D: b!(XEP)),    op!(0x3E: b!(XEP)),                      op!(0x3F: b!(XEP)),
        op!(0x40: b!(XEP)),                     op!(0x41: b!(XEP)),                     op!(0x42: b!(XEP)),                     op!(0x43: b!(XEP)),                     op!(0x44: b!(XEP)),                     op!(0x45: b!(XEP)),                     op!(0x46: b!(LD), rg!(B), rx!(X.b)),    op!(0x47: b!(XEP)),                     op!(0x48: b!(XEP)),    op!(0x49: b!(XEP)),                     op!(0x4A: b!(XEP)),                    op!(0x4B: b!(XEP)),            op!(0x4C: b!(XEP)),    op!(0x4D: b!(XEP)),    op!(0x4E: b!(LD), rg!(C), rx!(X.b)),     op!(0x4F: b!(XEP)),
        op!(0x50: b!(XEP)),                     op!(0x51: b!(XEP)),                     op!(0x52: b!(XEP)),                     op!(0x53: b!(XEP)),                     op!(0x54: b!(XEP)),                     op!(0x55: b!(XEP)),                     op!(0x56: b!(LD), rg!(D), rx!(X.b)),    op!(0x57: b!(XEP)),                     op!(0x58: b!(XEP)),    op!(0x59: b!(XEP)),                     op!(0x5A: b!(XEP)),                    op!(0x5B: b!(XEP)),            op!(0x5C: b!(XEP)),    op!(0x5D: b!(XEP)),    op!(0x5E: b!(LD), rg!(E), rx!(X.b)),     op!(0x5F: b!(XEP)),
        op!(0x60: b!(XEP)),                     op!(0x61: b!(XEP)),                     op!(0x62: b!(XEP)),                     op!(0x63: b!(XEP)),                     op!(0x64: b!(XEP)),                     op!(0x65: b!(XEP)),                     op!(0x66: b!(LD), rg!(H), rx!(X.b)),    op!(0x67: b!(XEP)),                     op!(0x68: b!(XEP)),    op!(0x69: b!(XEP)),                     op!(0x6A: b!(XEP)),                    op!(0x6B: b!(XEP)),            op!(0x6C: b!(XEP)),    op!(0x6D: b!(XEP)),    op!(0x6E: b!(LD), rg!(L), rx!(X.b)),     op!(0x6F: b!(XEP)),
        op!(0x70: b!(LD), rx!(X.b), rg!(B)),    op!(0x71: b!(LD), rx!(X.b), rg!(C)),    op!(0x72: b!(LD), rx!(X.b), rg!(D)),    op!(0x73: b!(LD), rx!(X.b), rg!(E)),    op!(0x74: b!(LD), rx!(X.b), rg!(H)),    op!(0x75: b!(LD), rx!(X.b), rg!(L)),    op!(0x76: b!(XEP)),                     op!(0x77: b!(LD), rx!(X.b), rg!(A)),    op!(0x78: b!(XEP)),    op!(0x79: b!(XEP)),                     op!(0x7A: b!(XEP)),                    op!(0x7B: b!(XEP)),            op!(0x7C: b!(XEP)),    op!(0x7D: b!(XEP)),    op!(0x7E: b!(LD), rg!(A), rx!(X.b)),     op!(0x7F: b!(XEP)),
        op!(0x80: b!(XEP)),                     op!(0x81: b!(XEP)),                     op!(0x82: b!(XEP)),                     op!(0x83: b!(XEP)),                     op!(0x84: b!(XEP)),                     op!(0x85: b!(XEP)),                     op!(0x86: b!(ADD), rg!(A), rx!(X.b)),   op!(0x87: b!(XEP)),                     op!(0x88: b!(XEP)),    op!(0x89: b!(XEP)),                     op!(0x8A: b!(XEP)),                    op!(0x8B: b!(XEP)),            op!(0x8C: b!(XEP)),    op!(0x8D: b!(XEP)),    op!(0x8E: b!(ADC), rg!(A), rx!(X.b)),    op!(0x8F: b!(XEP)),
        op!(0x90: b!(XEP)),                     op!(0x91: b!(XEP)),                     op!(0x92: b!(XEP)),                     op!(0x93: b!(XEP)),                     op!(0x94: b!(XEP)),                     op!(0x95: b!(XEP)),                     op!(0x96: b!(SUB), rg!(A), rx!(X.b)),   op!(0x97: b!(XEP)),                     op!(0x98: b!(XEP)),    op!(0x99: b!(XEP)),                     op!(0x9A: b!(XEP)),                    op!(0x9B: b!(XEP)),            op!(0x9C: b!(XEP)),    op!(0x9D: b!(XEP)),    op!(0x9E: b!(SBC), rg!(A), rx!(X.b)),    op!(0x9F: b!(XEP)),
        op!(0xA0: b!(XEP)),                     op!(0xA1: b!(XEP)),                     op!(0xA2: b!(XEP)),                     op!(0xA3: b!(XEP)),                     op!(0xA4: b!(XEP)),                     op!(0xA5: b!(XEP)),                     op!(0xA6: b!(AND), rg!(A), rx!(X.b)),   op!(0xA7: b!(XEP)),                     op!(0xA8: b!(XEP)),    op!(0xA9: b!(XEP)),                     op!(0xAA: b!(XEP)),                    op!(0xAB: b!(XEP)),            op!(0xAC: b!(XEP)),    op!(0xAD: b!(XEP)),    op!(0xAE: b!(XOR), rg!(A), rx!(X.b)),    op!(0xAF: b!(XEP)),
        op!(0xB0: b!(XEP)),                     op!(0xB1: b!(XEP)),                     op!(0xB2: b!(XEP)),                     op!(0xB3: b!(XEP)),                     op!(0xB4: b!(XEP)),                     op!(0xB5: b!(XEP)),                     op!(0xB6: b!(OR), rg!(A), rx!(X.b)),    op!(0xB7: b!(XEP)),                     op!(0xB8: b!(XEP)),    op!(0xB9: b!(XEP)),                     op!(0xBA: b!(XEP)),                    op!(0xBB: b!(XEP)),            op!(0xBC: b!(XEP)),    op!(0xBD: b!(XEP)),    op!(0xBE: b!(CP), rg!(A), rx!(X.b)),     op!(0xBF: b!(XEP)),
        op!(0xC0: b!(XEP)),                     op!(0xC1: b!(XEP)),                     op!(0xC2: b!(XEP)),                     op!(0xC3: b!(XEP)),                     op!(0xC4: b!(XEP)),                     op!(0xC5: b!(XEP)),                     op!(0xC6: b!(XEP)),                     op!(0xC7: b!(XEP)),                     op!(0xC8: b!(XEP)),    op!(0xC9: b!(XEP)),                     op!(0xCA: b!(XEP)),                    op!(0xCB: b!(XEP)),            op!(0xCC: b!(XEP)),    op!(0xCD: b!(XEP)),    op!(0xCE: b!(XEP)),                      op!(0xCF: b!(XEP)),
        op!(0xD0: b!(XEP)),                     op!(0xD1: b!(XEP)),                     op!(0xD2: b!(XEP)),                     op!(0xD3: b!(XEP)),                     op!(0xD4: b!(XEP)),                     op!(0xD5: b!(XEP)),                     op!(0xD6: b!(XEP)),                     op!(0xD7: b!(XEP)),                     op!(0xD8: b!(XEP)),    op!(0xD9: b!(XEP)),                     op!(0xDA: b!(XEP)),                    op!(0xDB: b!(XEP)),            op!(0xDC: b!(XEP)),    op!(0xDD: b!(XEP)),    op!(0xDE: b!(XEP)),                      op!(0xDF: b!(XEP)),
        op!(0xE0: b!(XEP)),                     op!(0xE1: b!(POP), rx!(X)),             op!(0xE2: b!(XEP)),                     op!(0xE3: b!(EX), sp!(w), rx!(X)),      op!(0xE4: b!(XEP)),                     op!(0xE5: b!(PUSH), rx!(X)),            op!(0xE6: b!(XEP)),                     op!(0xE7: b!(XEP)),                     op!(0xE8: b!(XEP)),    op!(0xE9: b!(JP UNC), rx!(X)),          op!(0xEA: b!(XEP)),                    op!(0xEB: b!(XEP)),            op!(0xEC: b!(XEP)),    op!(0xED: b!(XEP)),    op!(0xEE: b!(XEP)),                      op!(0xEF: b!(XEP)),
        op!(0xF0: b!(XEP)),                     op!(0xF1: b!(XEP)),                     op!(0xF2: b!(XEP)),                     op!(0xF3: b!(XEP)),                     op!(0xF4: b!(XEP)),                     op!(0xF5: b!(XEP)),                     op!(0xF6: b!(XEP)),                     op!(0xF7: b!(XEP)),                     op!(0xF8: b!(XEP)),    op!(0xF9: b!(LD), sp!(), rx!(X)),       op!(0xFA: b!(XEP)),                    op!(0xFB: b!(XEP)),            op!(0xFC: b!(XEP)),    op!(0xFD: b!(XEP)),    op!(0xFE: b!(XEP)),                      op!(0xFF: b!(XEP)),
    ]
}

pub(crate) fn fd_opcode_table<T>() -> [Operation<T>; 0x100] where T: 'static + BusZ80 {
    [
        op!(0x00: b!(XEP)),                     op!(0x01: b!(XEP)),                     op!(0x02: b!(XEP)),                     op!(0x03: b!(XEP)),                     op!(0x04: b!(XEP)),                     op!(0x05: b!(XEP)),                     op!(0x06: b!(XEP)),                     op!(0x07: b!(XEP)),                     op!(0x08: b!(XEP)),    op!(0x09: b!(ADD), rx!(Y), rg!(BC)),    op!(0x0A: b!(XEP)),                    op!(0x0B: b!(XEP)),            op!(0x0C: b!(XEP)),    op!(0x0D: b!(XEP)),    op!(0x0E: b!(XEP)),                      op!(0x0F: b!(XEP)),
        op!(0x10: b!(XEP)),                     op!(0x11: b!(XEP)),                     op!(0x12: b!(XEP)),                     op!(0x13: b!(XEP)),                     op!(0x14: b!(XEP)),                     op!(0x15: b!(XEP)),                     op!(0x16: b!(XEP)),                     op!(0x17: b!(XEP)),                     op!(0x18: b!(XEP)),    op!(0x19: b!(ADD), rx!(Y), rg!(DE)),    op!(0x1A: b!(XEP)),                    op!(0x1B: b!(XEP)),            op!(0x1C: b!(XEP)),    op!(0x1D: b!(XEP)),    op!(0x1E: b!(XEP)),                      op!(0x1F: b!(XEP)),
        op!(0x20: b!(XEP)),                     op!(0x21: b!(LD), rx!(Y), am!(DD)),     op!(0x22: b!(LD), am!(DD), rx!(Y)),     op!(0x23: b!(INC), rx!(Y)),             op!(0x24: b!(XEP)),                     op!(0x25: b!(XEP)),                     op!(0x26: b!(XEP)),                     op!(0x27: b!(XEP)),                     op!(0x28: b!(XEP)),    op!(0x29: b!(ADD), rx!(Y), rx!(Y)),     op!(0x2A: b!(LD), rx!(Y), am!(DD)),    op!(0x2B: b!(DEC), rx!(Y)),    op!(0x2C: b!(XEP)),    op!(0x2D: b!(XEP)),    op!(0x2E: b!(XEP)),                      op!(0x2F: b!(XEP)),
        op!(0x30: b!(XEP)),                     op!(0x31: b!(XEP)),                     op!(0x32: b!(XEP)),                     op!(0x33: b!(XEP)),                     op!(0x34: b!(INC), rx!(Y.b)),           op!(0x35: b!(DEC), rx!(Y.b)),           op!(0x36: b!(LD), rx!(Y.b), am!(D)),    op!(0x37: b!(XEP)),                     op!(0x38: b!(XEP)),    op!(0x39: b!(ADD), rx!(Y), sp!()),      op!(0x3A: b!(XEP)),                    op!(0x3B: b!(XEP)),            op!(0x3C: b!(XEP)),    op!(0x3D: b!(XEP)),    op!(0x3E: b!(XEP)),                      op!(0x3F: b!(XEP)),
        op!(0x40: b!(XEP)),                     op!(0x41: b!(XEP)),                     op!(0x42: b!(XEP)),                     op!(0x43: b!(XEP)),                     op!(0x44: b!(XEP)),                     op!(0x45: b!(XEP)),                     op!(0x46: b!(LD), rg!(B), rx!(Y.b)),    op!(0x47: b!(XEP)),                     op!(0x48: b!(XEP)),    op!(0x49: b!(XEP)),                     op!(0x4A: b!(XEP)),                    op!(0x4B: b!(XEP)),            op!(0x4C: b!(XEP)),    op!(0x4D: b!(XEP)),    op!(0x4E: b!(LD), rg!(C), rx!(Y.b)),     op!(0x4F: b!(XEP)),
        op!(0x50: b!(XEP)),                     op!(0x51: b!(XEP)),                     op!(0x52: b!(XEP)),                     op!(0x53: b!(XEP)),                     op!(0x54: b!(XEP)),                     op!(0x55: b!(XEP)),                     op!(0x56: b!(LD), rg!(D), rx!(Y.b)),    op!(0x57: b!(XEP)),                     op!(0x58: b!(XEP)),    op!(0x59: b!(XEP)),                     op!(0x5A: b!(XEP)),                    op!(0x5B: b!(XEP)),            op!(0x5C: b!(XEP)),    op!(0x5D: b!(XEP)),    op!(0x5E: b!(LD), rg!(E), rx!(Y.b)),     op!(0x5F: b!(XEP)),
        op!(0x60: b!(XEP)),                     op!(0x61: b!(XEP)),                     op!(0x62: b!(XEP)),                     op!(0x63: b!(XEP)),                     op!(0x64: b!(XEP)),                     op!(0x65: b!(XEP)),                     op!(0x66: b!(LD), rg!(H), rx!(Y.b)),    op!(0x67: b!(XEP)),                     op!(0x68: b!(XEP)),    op!(0x69: b!(XEP)),                     op!(0x6A: b!(XEP)),                    op!(0x6B: b!(XEP)),            op!(0x6C: b!(XEP)),    op!(0x6D: b!(XEP)),    op!(0x6E: b!(LD), rg!(L), rx!(Y.b)),     op!(0x6F: b!(XEP)),
        op!(0x70: b!(LD), rx!(Y.b), rg!(B)),    op!(0x71: b!(LD), rx!(Y.b), rg!(C)),    op!(0x72: b!(LD), rx!(Y.b), rg!(D)),    op!(0x73: b!(LD), rx!(Y.b), rg!(E)),    op!(0x74: b!(LD), rx!(Y.b), rg!(H)),    op!(0x75: b!(LD), rx!(Y.b), rg!(L)),    op!(0x76: b!(XEP)),                     op!(0x77: b!(LD), rx!(Y.b), rg!(A)),    op!(0x78: b!(XEP)),    op!(0x79: b!(XEP)),                     op!(0x7A: b!(XEP)),                    op!(0x7B: b!(XEP)),            op!(0x7C: b!(XEP)),    op!(0x7D: b!(XEP)),    op!(0x7E: b!(LD), rg!(A), rx!(Y.b)),     op!(0x7F: b!(XEP)),
        op!(0x80: b!(XEP)),                     op!(0x81: b!(XEP)),                     op!(0x82: b!(XEP)),                     op!(0x83: b!(XEP)),                     op!(0x84: b!(XEP)),                     op!(0x85: b!(XEP)),                     op!(0x86: b!(ADD), rg!(A), rx!(Y.b)),   op!(0x87: b!(XEP)),                     op!(0x88: b!(XEP)),    op!(0x89: b!(XEP)),                     op!(0x8A: b!(XEP)),                    op!(0x8B: b!(XEP)),            op!(0x8C: b!(XEP)),    op!(0x8D: b!(XEP)),    op!(0x8E: b!(ADC), rg!(A), rx!(Y.b)),    op!(0x8F: b!(XEP)),
        op!(0x90: b!(XEP)),                     op!(0x91: b!(XEP)),                     op!(0x92: b!(XEP)),                     op!(0x93: b!(XEP)),                     op!(0x94: b!(XEP)),                     op!(0x95: b!(XEP)),                     op!(0x96: b!(SUB), rg!(A), rx!(Y.b)),   op!(0x97: b!(XEP)),                     op!(0x98: b!(XEP)),    op!(0x99: b!(XEP)),                     op!(0x9A: b!(XEP)),                    op!(0x9B: b!(XEP)),            op!(0x9C: b!(XEP)),    op!(0x9D: b!(XEP)),    op!(0x9E: b!(SBC), rg!(A), rx!(Y.b)),    op!(0x9F: b!(XEP)),
        op!(0xA0: b!(XEP)),                     op!(0xA1: b!(XEP)),                     op!(0xA2: b!(XEP)),                     op!(0xA3: b!(XEP)),                     op!(0xA4: b!(XEP)),                     op!(0xA5: b!(XEP)),                     op!(0xA6: b!(AND), rg!(A), rx!(Y.b)),   op!(0xA7: b!(XEP)),                     op!(0xA8: b!(XEP)),    op!(0xA9: b!(XEP)),                     op!(0xAA: b!(XEP)),                    op!(0xAB: b!(XEP)),            op!(0xAC: b!(XEP)),    op!(0xAD: b!(XEP)),    op!(0xAE: b!(XOR), rg!(A), rx!(Y.b)),    op!(0xAF: b!(XEP)),
        op!(0xB0: b!(XEP)),                     op!(0xB1: b!(XEP)),                     op!(0xB2: b!(XEP)),                     op!(0xB3: b!(XEP)),                     op!(0xB4: b!(XEP)),                     op!(0xB5: b!(XEP)),                     op!(0xB6: b!(OR), rg!(A), rx!(Y.b)),    op!(0xB7: b!(XEP)),                     op!(0xB8: b!(XEP)),    op!(0xB9: b!(XEP)),                     op!(0xBA: b!(XEP)),                    op!(0xBB: b!(XEP)),            op!(0xBC: b!(XEP)),    op!(0xBD: b!(XEP)),    op!(0xBE: b!(CP), rg!(A), rx!(Y.b)),     op!(0xBF: b!(XEP)),
        op!(0xC0: b!(XEP)),                     op!(0xC1: b!(XEP)),                     op!(0xC2: b!(XEP)),                     op!(0xC3: b!(XEP)),                     op!(0xC4: b!(XEP)),                     op!(0xC5: b!(XEP)),                     op!(0xC6: b!(XEP)),                     op!(0xC7: b!(XEP)),                     op!(0xC8: b!(XEP)),    op!(0xC9: b!(XEP)),                     op!(0xCA: b!(XEP)),                    op!(0xCB: b!(XEP)),            op!(0xCC: b!(XEP)),    op!(0xCD: b!(XEP)),    op!(0xCE: b!(XEP)),                      op!(0xCF: b!(XEP)),
        op!(0xD0: b!(XEP)),                     op!(0xD1: b!(XEP)),                     op!(0xD2: b!(XEP)),                     op!(0xD3: b!(XEP)),                     op!(0xD4: b!(XEP)),                     op!(0xD5: b!(XEP)),                     op!(0xD6: b!(XEP)),                     op!(0xD7: b!(XEP)),                     op!(0xD8: b!(XEP)),    op!(0xD9: b!(XEP)),                     op!(0xDA: b!(XEP)),                    op!(0xDB: b!(XEP)),            op!(0xDC: b!(XEP)),    op!(0xDD: b!(XEP)),    op!(0xDE: b!(XEP)),                      op!(0xDF: b!(XEP)),
        op!(0xE0: b!(XEP)),                     op!(0xE1: b!(POP), rx!(Y)),             op!(0xE2: b!(XEP)),                     op!(0xE3: b!(EX), sp!(w), rx!(Y)),      op!(0xE4: b!(XEP)),                     op!(0xE5: b!(PUSH), rx!(Y)),            op!(0xE6: b!(XEP)),                     op!(0xE7: b!(XEP)),                     op!(0xE8: b!(XEP)),    op!(0xE9: b!(JP UNC), rx!(Y)),          op!(0xEA: b!(XEP)),                    op!(0xEB: b!(XEP)),            op!(0xEC: b!(XEP)),    op!(0xED: b!(XEP)),    op!(0xEE: b!(XEP)),                      op!(0xEF: b!(XEP)),
        op!(0xF0: b!(XEP)),                     op!(0xF1: b!(XEP)),                     op!(0xF2: b!(XEP)),                     op!(0xF3: b!(XEP)),                     op!(0xF4: b!(XEP)),                     op!(0xF5: b!(XEP)),                     op!(0xF6: b!(XEP)),                     op!(0xF7: b!(XEP)),                     op!(0xF8: b!(XEP)),    op!(0xF9: b!(LD), sp!(), rx!(Y)),       op!(0xFA: b!(XEP)),                    op!(0xFB: b!(XEP)),            op!(0xFC: b!(XEP)),    op!(0xFD: b!(XEP)),    op!(0xFE: b!(XEP)),                      op!(0xFF: b!(XEP)),
    ]
}

pub(crate) fn ddcb_opcode_table<T>() -> [Operation<T>; 0x100] where T: 'static + BusZ80 {
    [
        op!(0x00: b!(XEP)),    op!(0x01: b!(XEP)),    op!(0x02: b!(XEP)),    op!(0x03: b!(XEP)),    op!(0x04: b!(XEP)),    op!(0x05: b!(XEP)),    op!(0x06: b!(RLC), rx!(X.b)),      op!(0x07: b!(XEP)),    op!(0x08: b!(XEP)),    op!(0x09: b!(XEP)),    op!(0x0A: b!(XEP)),    op!(0x0B: b!(XEP)),    op!(0x0C: b!(XEP)),    op!(0x0D: b!(XEP)),    op!(0x0E: b!(RRC), rx!(X.b)),      op!(0x0F: b!(XEP)),
        op!(0x10: b!(XEP)),    op!(0x11: b!(XEP)),    op!(0x12: b!(XEP)),    op!(0x13: b!(XEP)),    op!(0x14: b!(XEP)),    op!(0x15: b!(XEP)),    op!(0x16: b!(RL), rx!(X.b)),       op!(0x17: b!(XEP)),    op!(0x18: b!(XEP)),    op!(0x19: b!(XEP)),    op!(0x1A: b!(XEP)),    op!(0x1B: b!(XEP)),    op!(0x1C: b!(XEP)),    op!(0x1D: b!(XEP)),    op!(0x1E: b!(RR), rx!(X.b)),       op!(0x1F: b!(XEP)),
        op!(0x20: b!(XEP)),    op!(0x21: b!(XEP)),    op!(0x22: b!(XEP)),    op!(0x23: b!(XEP)),    op!(0x24: b!(XEP)),    op!(0x25: b!(XEP)),    op!(0x26: b!(SLA), rx!(X.b)),      op!(0x27: b!(XEP)),    op!(0x28: b!(XEP)),    op!(0x29: b!(XEP)),    op!(0x2A: b!(XEP)),    op!(0x2B: b!(XEP)),    op!(0x2C: b!(XEP)),    op!(0x2D: b!(XEP)),    op!(0x2E: b!(SRA), rx!(X.b)),      op!(0x2F: b!(XEP)),
        op!(0x30: b!(XEP)),    op!(0x31: b!(XEP)),    op!(0x32: b!(XEP)),    op!(0x33: b!(XEP)),    op!(0x34: b!(XEP)),    op!(0x35: b!(XEP)),    op!(0x36: b!(XEP)),                op!(0x37: b!(XEP)),    op!(0x38: b!(XEP)),    op!(0x39: b!(XEP)),    op!(0x3A: b!(XEP)),    op!(0x3B: b!(XEP)),    op!(0x3C: b!(XEP)),    op!(0x3D: b!(XEP)),    op!(0x3E: b!(SRL), rx!(X.b)),      op!(0x3F: b!(XEP)),
        op!(0x40: b!(XEP)),    op!(0x41: b!(XEP)),    op!(0x42: b!(XEP)),    op!(0x43: b!(XEP)),    op!(0x44: b!(XEP)),    op!(0x45: b!(XEP)),    op!(0x46: b!(BIT 0), rx!(X.b)),    op!(0x47: b!(XEP)),    op!(0x48: b!(XEP)),    op!(0x49: b!(XEP)),    op!(0x4A: b!(XEP)),    op!(0x4B: b!(XEP)),    op!(0x4C: b!(XEP)),    op!(0x4D: b!(XEP)),    op!(0x4E: b!(BIT 1), rx!(X.b)),    op!(0x4F: b!(XEP)),
        op!(0x50: b!(XEP)),    op!(0x51: b!(XEP)),    op!(0x52: b!(XEP)),    op!(0x53: b!(XEP)),    op!(0x54: b!(XEP)),    op!(0x55: b!(XEP)),    op!(0x56: b!(BIT 2), rx!(X.b)),    op!(0x57: b!(XEP)),    op!(0x58: b!(XEP)),    op!(0x59: b!(XEP)),    op!(0x5A: b!(XEP)),    op!(0x5B: b!(XEP)),    op!(0x5C: b!(XEP)),    op!(0x5D: b!(XEP)),    op!(0x5E: b!(BIT 3), rx!(X.b)),    op!(0x5F: b!(XEP)),
        op!(0x60: b!(XEP)),    op!(0x61: b!(XEP)),    op!(0x62: b!(XEP)),    op!(0x63: b!(XEP)),    op!(0x64: b!(XEP)),    op!(0x65: b!(XEP)),    op!(0x66: b!(BIT 4), rx!(X.b)),    op!(0x67: b!(XEP)),    op!(0x68: b!(XEP)),    op!(0x69: b!(XEP)),    op!(0x6A: b!(XEP)),    op!(0x6B: b!(XEP)),    op!(0x6C: b!(XEP)),    op!(0x6D: b!(XEP)),    op!(0x6E: b!(BIT 5), rx!(X.b)),    op!(0x6F: b!(XEP)),
        op!(0x70: b!(XEP)),    op!(0x71: b!(XEP)),    op!(0x72: b!(XEP)),    op!(0x73: b!(XEP)),    op!(0x74: b!(XEP)),    op!(0x75: b!(XEP)),    op!(0x76: b!(BIT 6), rx!(X.b)),    op!(0x77: b!(XEP)),    op!(0x78: b!(XEP)),    op!(0x79: b!(XEP)),    op!(0x7A: b!(XEP)),    op!(0x7B: b!(XEP)),    op!(0x7C: b!(XEP)),    op!(0x7D: b!(XEP)),    op!(0x7E: b!(BIT 7), rx!(X.b)),    op!(0x7F: b!(XEP)),
        op!(0x80: b!(XEP)),    op!(0x81: b!(XEP)),    op!(0x82: b!(XEP)),    op!(0x83: b!(XEP)),    op!(0x84: b!(XEP)),    op!(0x85: b!(XEP)),    op!(0x86: b!(RES 0), rx!(X.b)),    op!(0x87: b!(XEP)),    op!(0x88: b!(XEP)),    op!(0x89: b!(XEP)),    op!(0x8A: b!(XEP)),    op!(0x8B: b!(XEP)),    op!(0x8C: b!(XEP)),    op!(0x8D: b!(XEP)),    op!(0x8E: b!(RES 1), rx!(X.b)),    op!(0x8F: b!(XEP)),
        op!(0x90: b!(XEP)),    op!(0x91: b!(XEP)),    op!(0x92: b!(XEP)),    op!(0x93: b!(XEP)),    op!(0x94: b!(XEP)),    op!(0x95: b!(XEP)),    op!(0x96: b!(RES 2), rx!(X.b)),    op!(0x97: b!(XEP)),    op!(0x98: b!(XEP)),    op!(0x99: b!(XEP)),    op!(0x9A: b!(XEP)),    op!(0x9B: b!(XEP)),    op!(0x9C: b!(XEP)),    op!(0x9D: b!(XEP)),    op!(0x9E: b!(RES 3), rx!(X.b)),    op!(0x9F: b!(XEP)),
        op!(0xA0: b!(XEP)),    op!(0xA1: b!(XEP)),    op!(0xA2: b!(XEP)),    op!(0xA3: b!(XEP)),    op!(0xA4: b!(XEP)),    op!(0xA5: b!(XEP)),    op!(0xA6: b!(RES 4), rx!(X.b)),    op!(0xA7: b!(XEP)),    op!(0xA8: b!(XEP)),    op!(0xA9: b!(XEP)),    op!(0xAA: b!(XEP)),    op!(0xAB: b!(XEP)),    op!(0xAC: b!(XEP)),    op!(0xAD: b!(XEP)),    op!(0xAE: b!(RES 5), rx!(X.b)),    op!(0xAF: b!(XEP)),
        op!(0xB0: b!(XEP)),    op!(0xB1: b!(XEP)),    op!(0xB2: b!(XEP)),    op!(0xB3: b!(XEP)),    op!(0xB4: b!(XEP)),    op!(0xB5: b!(XEP)),    op!(0xB6: b!(RES 6), rx!(X.b)),    op!(0xB7: b!(XEP)),    op!(0xB8: b!(XEP)),    op!(0xB9: b!(XEP)),    op!(0xBA: b!(XEP)),    op!(0xBB: b!(XEP)),    op!(0xBC: b!(XEP)),    op!(0xBD: b!(XEP)),    op!(0xBE: b!(RES 7), rx!(X.b)),    op!(0xBF: b!(XEP)),
        op!(0xC0: b!(XEP)),    op!(0xC1: b!(XEP)),    op!(0xC2: b!(XEP)),    op!(0xC3: b!(XEP)),    op!(0xC4: b!(XEP)),    op!(0xC5: b!(XEP)),    op!(0xC6: b!(SET 0), rx!(X.b)),    op!(0xC7: b!(XEP)),    op!(0xC8: b!(XEP)),    op!(0xC9: b!(XEP)),    op!(0xCA: b!(XEP)),    op!(0xCB: b!(XEP)),    op!(0xCC: b!(XEP)),    op!(0xCD: b!(XEP)),    op!(0xCE: b!(SET 1), rx!(X.b)),    op!(0xCF: b!(XEP)),
        op!(0xD0: b!(XEP)),    op!(0xD1: b!(XEP)),    op!(0xD2: b!(XEP)),    op!(0xD3: b!(XEP)),    op!(0xD4: b!(XEP)),    op!(0xD5: b!(XEP)),    op!(0xD6: b!(SET 2), rx!(X.b)),    op!(0xD7: b!(XEP)),    op!(0xD8: b!(XEP)),    op!(0xD9: b!(XEP)),    op!(0xDA: b!(XEP)),    op!(0xDB: b!(XEP)),    op!(0xDC: b!(XEP)),    op!(0xDD: b!(XEP)),    op!(0xDE: b!(SET 3), rx!(X.b)),    op!(0xDF: b!(XEP)),
        op!(0xE0: b!(XEP)),    op!(0xE1: b!(XEP)),    op!(0xE2: b!(XEP)),    op!(0xE3: b!(XEP)),    op!(0xE4: b!(XEP)),    op!(0xE5: b!(XEP)),    op!(0xE6: b!(SET 4), rx!(X.b)),    op!(0xE7: b!(XEP)),    op!(0xE8: b!(XEP)),    op!(0xE9: b!(XEP)),    op!(0xEA: b!(XEP)),    op!(0xEB: b!(XEP)),    op!(0xEC: b!(XEP)),    op!(0xED: b!(XEP)),    op!(0xEE: b!(SET 5), rx!(X.b)),    op!(0xEF: b!(XEP)),
        op!(0xF0: b!(XEP)),    op!(0xF1: b!(XEP)),    op!(0xF2: b!(XEP)),    op!(0xF3: b!(XEP)),    op!(0xF4: b!(XEP)),    op!(0xF5: b!(XEP)),    op!(0xF6: b!(SET 6), rx!(X.b)),    op!(0xF7: b!(XEP)),    op!(0xF8: b!(XEP)),    op!(0xF9: b!(XEP)),    op!(0xFA: b!(XEP)),    op!(0xFB: b!(XEP)),    op!(0xFC: b!(XEP)),    op!(0xFD: b!(XEP)),    op!(0xFE: b!(SET 7), rx!(X.b)),    op!(0xFF: b!(XEP)),
    ]
}

pub(crate) fn fdcb_opcode_table<T>() -> [Operation<T>; 0x100] where T: 'static + BusZ80 {
    [
        op!(0x00: b!(RLC), rx!(Y.b), rg!(B)),       op!(0x01: b!(RLC), rx!(Y.b), rg!(C)),      op!(0x02: b!(RLC), rx!(Y.b), rg!(D)),       op!(0x03: b!(RLC), rx!(Y.b), rg!(E)),       op!(0x04: b!(RLC), rx!(Y.b), rg!(H)),       op!(0x05: b!(RLC), rx!(Y.b), rg!(L)),       op!(0x06: b!(RLC), rx!(Y.b)),       op!(0x07: b!(RLC), rx!(Y.b), rg!(A)),       op!(0x08: b!(RRC), rx!(Y.b), rg!(B)),       op!(0x09: b!(RRC), rx!(Y.b), rg!(C)),       op!(0x0A: b!(RRC), rx!(Y.b), rg!(D)),       op!(0x0B: b!(RRC), rx!(Y.b), rg!(E)),       op!(0x0C: b!(RRC), rx!(Y.b), rg!(H)),       op!(0x0D: b!(RRC), rx!(Y.b), rg!(L)),       op!(0x0E: b!(RRC), rx!(Y.b)),       op!(0x0F: b!(RRC), rx!(Y.b), rg!(A)),
        op!(0x10: b!(RL), rx!(Y.b), rg!(B)),        op!(0x11: b!(RL), rx!(Y.b), rg!(C)),       op!(0x12: b!(RL), rx!(Y.b), rg!(D)),        op!(0x13: b!(RL), rx!(Y.b), rg!(E)),        op!(0x14: b!(RL), rx!(Y.b), rg!(H)),        op!(0x15: b!(RL), rx!(Y.b), rg!(L)),        op!(0x16: b!(RL), rx!(Y.b)),        op!(0x17: b!(RL), rx!(Y.b), rg!(A)),        op!(0x18: b!(RR), rx!(Y.b), rg!(B)),        op!(0x19: b!(RR), rx!(Y.b), rg!(C)),        op!(0x1A: b!(RR), rx!(Y.b), rg!(D)),        op!(0x1B: b!(RR), rx!(Y.b), rg!(E)),        op!(0x1C: b!(RR), rx!(Y.b), rg!(H)),        op!(0x1D: b!(RR), rx!(Y.b), rg!(L)),        op!(0x1E: b!(RR), rx!(Y.b)),        op!(0x1F: b!(RR), rx!(Y.b), rg!(A)),
        op!(0x20: b!(SLA), rx!(Y.b), rg!(B)),       op!(0x21: b!(SLA), rx!(Y.b), rg!(C)),      op!(0x22: b!(SLA), rx!(Y.b), rg!(D)),       op!(0x23: b!(SLA), rx!(Y.b), rg!(E)),       op!(0x24: b!(SLA), rx!(Y.b), rg!(H)),       op!(0x25: b!(SLA), rx!(Y.b), rg!(L)),       op!(0x26: b!(SLA), rx!(Y.b)),       op!(0x27: b!(SLA), rx!(Y.b), rg!(A)),       op!(0x28: b!(SRA), rx!(Y.b), rg!(B)),       op!(0x29: b!(SRA), rx!(Y.b), rg!(C)),       op!(0x2A: b!(SRA), rx!(Y.b), rg!(D)),       op!(0x2B: b!(SRA), rx!(Y.b), rg!(E)),       op!(0x2C: b!(SRA), rx!(Y.b), rg!(H)),       op!(0x2D: b!(SRA), rx!(Y.b), rg!(L)),       op!(0x2E: b!(SRA), rx!(Y.b)),       op!(0x2F: b!(SRA), rx!(Y.b), rg!(A)),
        op!(0x30: b!(SLL), rx!(Y.b), rg!(B)),       op!(0x31: b!(SLL), rx!(Y.b), rg!(C)),      op!(0x32: b!(SLL), rx!(Y.b), rg!(D)),       op!(0x33: b!(SLL), rx!(Y.b), rg!(E)),       op!(0x34: b!(SLL), rx!(Y.b), rg!(H)),       op!(0x35: b!(SLL), rx!(Y.b), rg!(L)),       op!(0x36: b!(SLL), rx!(Y.b)),       op!(0x37: b!(SLL), rx!(Y.b), rg!(A)),       op!(0x38: b!(SRL), rx!(Y.b), rg!(B)),       op!(0x39: b!(SRL), rx!(Y.b), rg!(C)),       op!(0x3A: b!(SRL), rx!(Y.b), rg!(D)),       op!(0x3B: b!(SRL), rx!(Y.b), rg!(E)),       op!(0x3C: b!(SRL), rx!(Y.b), rg!(H)),       op!(0x3D: b!(SRL), rx!(Y.b), rg!(L)),       op!(0x3E: b!(SRL), rx!(Y.b)),       op!(0x3F: b!(SRL), rx!(Y.b), rg!(A)),
        op!(0x40: b!(BIT 0), rx!(Y.b)),             op!(0x41: b!(BIT 0), rx!(Y.b)),            op!(0x42: b!(BIT 0), rx!(Y.b)),             op!(0x43: b!(BIT 0), rx!(Y.b)),             op!(0x44: b!(BIT 0), rx!(Y.b)),             op!(0x45: b!(BIT 0), rx!(Y.b)),             op!(0x46: b!(BIT 0), rx!(Y.b)),     op!(0x47: b!(BIT 0), rx!(Y.b)),             op!(0x48: b!(BIT 1), rx!(Y.b)),             op!(0x49: b!(BIT 1), rx!(Y.b)),             op!(0x4A: b!(BIT 1), rx!(Y.b)),             op!(0x4B: b!(BIT 1), rx!(Y.b)),             op!(0x4C: b!(BIT 1), rx!(Y.b)),             op!(0x4D: b!(BIT 1), rx!(Y.b)),             op!(0x4E: b!(BIT 1), rx!(Y.b)),     op!(0x4F: b!(BIT 1), rx!(Y.b)),
        op!(0x50: b!(BIT 2), rx!(Y.b)),             op!(0x51: b!(BIT 2), rx!(Y.b)),            op!(0x52: b!(BIT 2), rx!(Y.b)),             op!(0x53: b!(BIT 2), rx!(Y.b)),             op!(0x54: b!(BIT 2), rx!(Y.b)),             op!(0x55: b!(BIT 2), rx!(Y.b)),             op!(0x56: b!(BIT 2), rx!(Y.b)),     op!(0x57: b!(BIT 2), rx!(Y.b)),             op!(0x58: b!(BIT 3), rx!(Y.b)),             op!(0x59: b!(BIT 3), rx!(Y.b)),             op!(0x5A: b!(BIT 3), rx!(Y.b)),             op!(0x5B: b!(BIT 3), rx!(Y.b)),             op!(0x5C: b!(BIT 3), rx!(Y.b)),             op!(0x5D: b!(BIT 3), rx!(Y.b)),             op!(0x5E: b!(BIT 3), rx!(Y.b)),     op!(0x5F: b!(BIT 3), rx!(Y.b)),
        op!(0x60: b!(BIT 4), rx!(Y.b)),             op!(0x61: b!(BIT 4), rx!(Y.b)),            op!(0x62: b!(BIT 4), rx!(Y.b)),             op!(0x63: b!(BIT 4), rx!(Y.b)),             op!(0x64: b!(BIT 4), rx!(Y.b)),             op!(0x65: b!(BIT 4), rx!(Y.b)),             op!(0x66: b!(BIT 4), rx!(Y.b)),     op!(0x67: b!(BIT 4), rx!(Y.b)),             op!(0x68: b!(BIT 5), rx!(Y.b)),             op!(0x69: b!(BIT 5), rx!(Y.b)),             op!(0x6A: b!(BIT 5), rx!(Y.b)),             op!(0x6B: b!(BIT 5), rx!(Y.b)),             op!(0x6C: b!(BIT 5), rx!(Y.b)),             op!(0x6D: b!(BIT 5), rx!(Y.b)),             op!(0x6E: b!(BIT 5), rx!(Y.b)),     op!(0x6F: b!(BIT 5), rx!(Y.b)),
        op!(0x70: b!(BIT 6), rx!(Y.b)),             op!(0x71: b!(BIT 6), rx!(Y.b)),            op!(0x72: b!(BIT 6), rx!(Y.b)),             op!(0x73: b!(BIT 6), rx!(Y.b)),             op!(0x74: b!(BIT 6), rx!(Y.b)),             op!(0x75: b!(BIT 6), rx!(Y.b)),             op!(0x76: b!(BIT 6), rx!(Y.b)),     op!(0x77: b!(BIT 6), rx!(Y.b)),             op!(0x78: b!(BIT 7), rx!(Y.b)),             op!(0x79: b!(BIT 7), rx!(Y.b)),             op!(0x7A: b!(BIT 7), rx!(Y.b)),             op!(0x7B: b!(BIT 7), rx!(Y.b)),             op!(0x7C: b!(BIT 7), rx!(Y.b)),             op!(0x7D: b!(BIT 7), rx!(Y.b)),             op!(0x7E: b!(BIT 7), rx!(Y.b)),     op!(0x7F: b!(BIT 7), rx!(Y.b)),
        op!(0x80: b!(RES 0), rx!(Y.b), rg!(B)),     op!(0x81: b!(RES 0),rx!(Y.b), rg!(C)),     op!(0x82: b!(RES 0), rx!(Y.b), rg!(D)),     op!(0x83: b!(RES 0), rx!(Y.b), rg!(E)),     op!(0x84: b!(RES 0), rx!(Y.b), rg!(H)),     op!(0x85: b!(RES 0), rx!(Y.b), rg!(L)),     op!(0x86: b!(RES 0), rx!(Y.b)),     op!(0x87: b!(RES 0), rx!(Y.b), rg!(A)),     op!(0x88: b!(RES 1), rx!(Y.b), rg!(B)),     op!(0x89: b!(RES 1), rx!(Y.b), rg!(C)),     op!(0x8A: b!(RES 1), rx!(Y.b), rg!(D)),     op!(0x8B: b!(RES 1), rx!(Y.b), rg!(E)),     op!(0x8C: b!(RES 1), rx!(Y.b), rg!(H)),     op!(0x8D: b!(RES 1), rx!(Y.b), rg!(L)),     op!(0x8E: b!(RES 1), rx!(Y.b)),     op!(0x8F: b!(RES 1), rx!(Y.b), rg!(A)),
        op!(0x90: b!(RES 2), rx!(Y.b), rg!(B)),     op!(0x91: b!(RES 2),rx!(Y.b), rg!(C)),     op!(0x92: b!(RES 2), rx!(Y.b), rg!(D)),     op!(0x93: b!(RES 2), rx!(Y.b), rg!(E)),     op!(0x94: b!(RES 2), rx!(Y.b), rg!(H)),     op!(0x95: b!(RES 2), rx!(Y.b), rg!(L)),     op!(0x96: b!(RES 2), rx!(Y.b)),     op!(0x97: b!(RES 2), rx!(Y.b), rg!(A)),     op!(0x98: b!(RES 3), rx!(Y.b), rg!(B)),     op!(0x99: b!(RES 3), rx!(Y.b), rg!(C)),     op!(0x9A: b!(RES 3), rx!(Y.b), rg!(D)),     op!(0x9B: b!(RES 3), rx!(Y.b), rg!(E)),     op!(0x9C: b!(RES 3), rx!(Y.b), rg!(H)),     op!(0x9D: b!(RES 3), rx!(Y.b), rg!(L)),     op!(0x9E: b!(RES 3), rx!(Y.b)),     op!(0x9F: b!(RES 3), rx!(Y.b), rg!(A)),
        op!(0xA0: b!(RES 4), rx!(Y.b), rg!(B)),     op!(0xA1: b!(RES 4),rx!(Y.b), rg!(C)),     op!(0xA2: b!(RES 4), rx!(Y.b), rg!(D)),     op!(0xA3: b!(RES 4), rx!(Y.b), rg!(E)),     op!(0xA4: b!(RES 4), rx!(Y.b), rg!(H)),     op!(0xA5: b!(RES 4), rx!(Y.b), rg!(L)),     op!(0xA6: b!(RES 4), rx!(Y.b)),     op!(0xA7: b!(RES 4), rx!(Y.b), rg!(A)),     op!(0xA8: b!(RES 5), rx!(Y.b), rg!(B)),     op!(0xA9: b!(RES 5), rx!(Y.b), rg!(C)),     op!(0xAA: b!(RES 5), rx!(Y.b), rg!(D)),     op!(0xAB: b!(RES 5), rx!(Y.b), rg!(E)),     op!(0xAC: b!(RES 5), rx!(Y.b), rg!(H)),     op!(0xAD: b!(RES 5), rx!(Y.b), rg!(L)),     op!(0xAE: b!(RES 5), rx!(Y.b)),     op!(0xAF: b!(RES 5), rx!(Y.b), rg!(A)),
        op!(0xB0: b!(RES 6), rx!(Y.b), rg!(B)),     op!(0xB1: b!(RES 6),rx!(Y.b), rg!(C)),     op!(0xB2: b!(RES 6), rx!(Y.b), rg!(D)),     op!(0xB3: b!(RES 6), rx!(Y.b), rg!(E)),     op!(0xB4: b!(RES 6), rx!(Y.b), rg!(H)),     op!(0xB5: b!(RES 6), rx!(Y.b), rg!(L)),     op!(0xB6: b!(RES 6), rx!(Y.b)),     op!(0xB7: b!(RES 6), rx!(Y.b), rg!(A)),     op!(0xB8: b!(RES 7), rx!(Y.b), rg!(B)),     op!(0xB9: b!(RES 7), rx!(Y.b), rg!(C)),     op!(0xBA: b!(RES 7), rx!(Y.b), rg!(D)),     op!(0xBB: b!(RES 7), rx!(Y.b), rg!(E)),     op!(0xBC: b!(RES 7), rx!(Y.b), rg!(H)),     op!(0xBD: b!(RES 7), rx!(Y.b), rg!(L)),     op!(0xBE: b!(RES 7), rx!(Y.b)),     op!(0xBF: b!(RES 7), rx!(Y.b), rg!(A)),
        op!(0xC0: b!(SET 0), rx!(Y.b), rg!(B)),     op!(0xC1: b!(SET 0),rx!(Y.b), rg!(C)),     op!(0xC2: b!(SET 0), rx!(Y.b), rg!(D)),     op!(0xC3: b!(SET 0), rx!(Y.b), rg!(E)),     op!(0xC4: b!(SET 0), rx!(Y.b), rg!(H)),     op!(0xC5: b!(SET 0), rx!(Y.b), rg!(L)),     op!(0xC6: b!(SET 0), rx!(Y.b)),     op!(0xC7: b!(SET 0), rx!(Y.b), rg!(A)),     op!(0xC8: b!(SET 1), rx!(Y.b), rg!(B)),     op!(0xC9: b!(SET 1), rx!(Y.b), rg!(C)),     op!(0xCA: b!(SET 1), rx!(Y.b), rg!(D)),     op!(0xCB: b!(SET 1), rx!(Y.b), rg!(E)),     op!(0xCC: b!(SET 1), rx!(Y.b), rg!(H)),     op!(0xCD: b!(SET 1), rx!(Y.b), rg!(L)),     op!(0xCE: b!(SET 1), rx!(Y.b)),     op!(0xCF: b!(SET 1), rx!(Y.b), rg!(A)),
        op!(0xD0: b!(SET 2), rx!(Y.b), rg!(B)),     op!(0xD1: b!(SET 2),rx!(Y.b), rg!(C)),     op!(0xD2: b!(SET 2), rx!(Y.b), rg!(D)),     op!(0xD3: b!(SET 2), rx!(Y.b), rg!(E)),     op!(0xD4: b!(SET 2), rx!(Y.b), rg!(H)),     op!(0xD5: b!(SET 2), rx!(Y.b), rg!(L)),     op!(0xD6: b!(SET 2), rx!(Y.b)),     op!(0xD7: b!(SET 2), rx!(Y.b), rg!(A)),     op!(0xD8: b!(SET 3), rx!(Y.b), rg!(B)),     op!(0xD9: b!(SET 3), rx!(Y.b), rg!(C)),     op!(0xDA: b!(SET 3), rx!(Y.b), rg!(D)),     op!(0xDB: b!(SET 3), rx!(Y.b), rg!(E)),     op!(0xDC: b!(SET 3), rx!(Y.b), rg!(H)),     op!(0xDD: b!(SET 3), rx!(Y.b), rg!(L)),     op!(0xDE: b!(SET 3), rx!(Y.b)),     op!(0xDF: b!(SET 3), rx!(Y.b), rg!(A)),
        op!(0xE0: b!(SET 4), rx!(Y.b), rg!(B)),     op!(0xE1: b!(SET 4),rx!(Y.b), rg!(C)),     op!(0xE2: b!(SET 4), rx!(Y.b), rg!(D)),     op!(0xE3: b!(SET 4), rx!(Y.b), rg!(E)),     op!(0xE4: b!(SET 4), rx!(Y.b), rg!(H)),     op!(0xE5: b!(SET 4), rx!(Y.b), rg!(L)),     op!(0xE6: b!(SET 4), rx!(Y.b)),     op!(0xE7: b!(SET 4), rx!(Y.b), rg!(A)),     op!(0xE8: b!(SET 5), rx!(Y.b), rg!(B)),     op!(0xE9: b!(SET 5), rx!(Y.b), rg!(C)),     op!(0xEA: b!(SET 5), rx!(Y.b), rg!(D)),     op!(0xEB: b!(SET 5), rx!(Y.b), rg!(E)),     op!(0xEC: b!(SET 5), rx!(Y.b), rg!(H)),     op!(0xED: b!(SET 5), rx!(Y.b), rg!(L)),     op!(0xEE: b!(SET 5), rx!(Y.b)),     op!(0xEF: b!(SET 5), rx!(Y.b), rg!(A)),
        op!(0xF0: b!(SET 6), rx!(Y.b), rg!(B)),     op!(0xF1: b!(SET 6),rx!(Y.b), rg!(C)),     op!(0xF2: b!(SET 6), rx!(Y.b), rg!(D)),     op!(0xF3: b!(SET 6), rx!(Y.b), rg!(E)),     op!(0xF4: b!(SET 6), rx!(Y.b), rg!(H)),     op!(0xF5: b!(SET 6), rx!(Y.b), rg!(L)),     op!(0xF6: b!(SET 6), rx!(Y.b)),     op!(0xF7: b!(SET 6), rx!(Y.b), rg!(A)),     op!(0xF8: b!(SET 7), rx!(Y.b), rg!(B)),     op!(0xF9: b!(SET 7), rx!(Y.b), rg!(C)),     op!(0xFA: b!(SET 7), rx!(Y.b), rg!(D)),     op!(0xFB: b!(SET 7), rx!(Y.b), rg!(E)),     op!(0xFC: b!(SET 7), rx!(Y.b), rg!(H)),     op!(0xFD: b!(SET 7), rx!(Y.b), rg!(L)),     op!(0xFE: b!(SET 7), rx!(Y.b)),     op!(0xFF: b!(SET 7), rx!(Y.b), rg!(A)),
    ]
}