[package]
name = "vdp_emu"
version = "0.1.0"
authors = ["zvoleg <oleg.zaitsevv@gmail.com>"]
edition = "2021"

[dependencies.m68k_emu]
path = "../m68k_emu"

[dependencies]
spriter = { git="https://github.com/zvoleg/spriter" }
rand = "*"